<h1>Chapter 3: Fast Array Operations with NumPy and Pandas</h1>

<h1>Getting started with NumPy</h1>
<h2>Creating arrays</h2>

In [5]:
# create a numpy array
import numpy as np
a = np.array([0, 1, 2])
a

array([0, 1, 2])

In [6]:
# inspect datatype
a.dtype

dtype('int32')

In [7]:
# change datatype
a = np.array([1, 2, 3], dtype='float32')
a.astype('float32')

array([ 1.,  2.,  3.], dtype=float32)

In [8]:
# create a 2D numpy array (= array in array)
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)

[[0 1 2]
 [3 4 5]]


In [9]:
# new array has 2 rows, 3 columns
a.shape

(2, 3)

In [10]:
# 1: create an array and reshape it next to multi-dimensional array
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 
             9, 10, 11, 12, 13, 14, 15])
a.shape

(16,)

In [11]:
# 2 reshape to 4x4 array
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
# create array filled with zeros
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [13]:
# create array filled with zeros
np.empty((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
# create array filled with ones
np.ones((3, 3), dtype='float32')

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [15]:
# create array filled with random integers between 0 and 1
np.random.rand(3, 3)

array([[ 0.9464486 ,  0.71046674,  0.96777608],
       [ 0.04026651,  0.73012033,  0.90086184],
       [ 0.27430755,  0.67480664,  0.63308175]])

In [16]:
# create array with same size as other array (1)
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# create array with same size as other array (2)
np.empty_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# create array with same size as other array (3)
np.ones_like(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h2>Accessing arrays</h2>

In [19]:
# NumPy arrays can be indexed using integers 
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
A[0]

0

In [20]:
# NumPy arrays can be iterated using a for loop
[a for a in A]

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [21]:
# A[0] returns the first row of multi-dimensional array
A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
A[0]

array([0, 1, 2])

In [22]:
# adding a comma indexes the same row, returning the second element of the first row
A[0, 1]

1

In [23]:
# equivalent version using tuple
A[(0, 1)]

1

In [24]:
# slice an array into multiple dimensions, in this case the first dimension, creating triplets
A[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
# slice newly sliced array again into multiple dimensions, resulting in a (2,2) array
A[0:2, 0:2]

array([[0, 1],
       [3, 4]])

In [26]:
# update array value using numerical index: first row, second column
A[0, 1] = 8

In [27]:
A

array([[0, 8, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# update array value using a slice
A[0:2, 0:2] = [[1, 1], [1, 1]]

In [29]:
A

array([[1, 1, 2],
       [1, 1, 5],
       [6, 7, 8]])

In [30]:
# NumPy slicing is fast as it returns a view from the same memory data
a = np.array([1, 1, 1, 1])
a_view = a[0:2]
a_view[0] = 2
print(a)

[2 1 1 1]


In [31]:
# example of slicing syntax of numpy array
# step 1: define array of ten rows, two columns with x-y coordinates
r_i = np.random.rand(10, 2)
r_i

array([[ 0.40494445,  0.68981745],
       [ 0.24217951,  0.75073032],
       [ 0.75905485,  0.02845574],
       [ 0.13907367,  0.97277194],
       [ 0.29383485,  0.6415592 ],
       [ 0.67488674,  0.87097062],
       [ 0.19633667,  0.93073169],
       [ 0.30031634,  0.64278415],
       [ 0.83314945,  0.27226685],
       [ 0.17498297,  0.99799608]])

In [32]:
# step 2: slice every index on the first axis = first column
x_i = r_i[:, 0]
x_i

array([ 0.40494445,  0.24217951,  0.75905485,  0.13907367,  0.29383485,
        0.67488674,  0.19633667,  0.30031634,  0.83314945,  0.17498297])

In [33]:
# step 3: returning only the first coordinate
r_0 = r_i[0, :]
r_0

array([ 0.40494445,  0.68981745])

In [34]:
# step 4, does the same as step 3
r_i[0]

array([ 0.40494445,  0.68981745])

In [35]:
# example of fancy indexing: indexing an array with another Numpy array
# step 1, define array and array used for indexing:
a = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
# values of update array are used as index positions on the first array
idx = np.array([0, 2, 3])
a[idx]

array([9, 7, 6])

In [36]:
a = np.array([[0, 1, 2], [3, 4, 5], 
              [6, 7, 8], [9, 10, 11]])
idx1 = np.array([0, 1])
idx2 = np.array([2, 2])
# returns second element of first dimension/row (=2), second element of second dimension/row (=5) 
a[idx1, idx2]

array([2, 5])

In [37]:
# is equivalent to a[[0, 1]], returns first and second rows
a[np.array([0,1])]

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
# using a tuple will works as index on multiple dimensions:
a[(2, 1)]

7

In [39]:
# select elements from original array in any shape, for example a (2,2) array
idx1 = [[0, 1], [3, 2]]
idx2 = [[0, 2], [1, 1]]
a[idx1, idx2]

array([[ 0,  5],
       [10,  7]])

In [40]:
# combining array slicing and fancy-indexing features, handy for swapping x and y values in next cell:
r_i = np.random.rand(10, 2)
r_i

array([[ 0.11433806,  0.29143583],
       [ 0.53974395,  0.60126961],
       [ 0.49372836,  0.88849423],
       [ 0.40398505,  0.18433041],
       [ 0.19199386,  0.03516159],
       [ 0.66709868,  0.03167498],
       [ 0.77134631,  0.70576819],
       [ 0.35524601,  0.72822307],
       [ 0.11322613,  0.63659832],
       [ 0.63725016,  0.33885752]])

In [41]:
# swapping x and y values
r_i[:, [0, 1]] = r_i[:, [1,0]]
r_i

array([[ 0.29143583,  0.11433806],
       [ 0.60126961,  0.53974395],
       [ 0.88849423,  0.49372836],
       [ 0.18433041,  0.40398505],
       [ 0.03516159,  0.19199386],
       [ 0.03167498,  0.66709868],
       [ 0.70576819,  0.77134631],
       [ 0.72822307,  0.35524601],
       [ 0.63659832,  0.11322613],
       [ 0.33885752,  0.63725016]])

In [42]:
# performance optimization using np.take and numpy.compress
r_i = np.random.rand(100, 2)
idx = np.arange(50) # integers 0 to 50
%timeit np.take(r_i, idx, axis=0)

2.51 µs ± 885 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [43]:
r_i = np.random.rand(100, 2)
idx = np.arange(50) # integers 0 to 50
%timeit r_i[idx]

2.87 µs ± 55.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [44]:
idx = np.ones(100, dtype='bool')
%timeit np.compress(idx, r_i, axis=0)

2.03 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [45]:
%timeit r_i[idx]

5.48 µs ± 703 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


<h2>Broadcasting</h2><br>
Broadcasting is a clever set of rules that enables fast array calculations for arrays of similar (but not equal!) shape.

In [46]:
# multiplying two arrays of equal shape
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A * B

array([[ 5, 12],
       [21, 32]])

In [47]:
# multiplying when shapes don´t match is no problem
A * 2

array([[2, 4],
       [6, 8]])

In [48]:
# NumPy adds one axis in B so that it is (5,1,2). Both arrays are compatible to perform a calculation.
A = np.random.rand(5, 10, 2)
B = np.random.rand(5, 2)
A * B[:, np.newaxis, :]

array([[[  6.37220400e-01,   1.64404258e-02],
        [  4.67449201e-01,   3.64976393e-02],
        [  4.87661945e-01,   4.22903254e-02],
        [  2.86379253e-01,   2.69063626e-02],
        [  5.29392250e-01,   4.52083835e-04],
        [  3.65997869e-01,   4.01405536e-02],
        [  9.90821240e-02,   3.61970703e-02],
        [  7.18600639e-02,   4.01821549e-02],
        [  5.04505867e-01,   1.78636370e-02],
        [  3.18849991e-01,   3.06971261e-02]],

       [[  1.92131194e-02,   4.83971703e-02],
        [  2.91488229e-02,   3.12215740e-01],
        [  4.79006959e-02,   2.58877480e-01],
        [  1.28473174e-01,   3.08206967e-01],
        [  9.80323025e-02,   7.83800034e-02],
        [  6.00085393e-02,   2.96422976e-01],
        [  3.04080439e-02,   2.62828072e-02],
        [  7.51685270e-02,   2.43032243e-01],
        [  8.31856699e-02,   2.99054423e-01],
        [  8.12718717e-02,   1.74496644e-01]],

       [[  2.82429952e-02,   8.88305250e-02],
        [  1.10911480e-01,   4

<h2>Mathematical operations</h2>

In [49]:
# take square root of every element in array
np.sqrt(np.array([4, 9, 16, 25]))


array([ 2.,  3.,  4.,  5.])

In [50]:
# use a > operator to obtain a bool array
a = np.random.rand(5, 3)
a > 0.3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [51]:
# resulting bool array can be reused an an index to retrieve elements greater than 0.5:
a[a > 0.5]
print(a[a > 0.5])

[ 0.91404038  0.67350777  0.73665123  0.97887093  0.8701391   0.7975995
  0.50151911  0.89576851]


In [52]:
# sum of column values
a = np.random.rand(5, 3)
a.sum(axis=0)

array([ 2.51603601,  3.66735784,  2.28357274])

In [53]:
# sum of row values
a.sum(axis=1)

array([ 1.83792233,  1.96529245,  1.47899817,  1.19497081,  1.98978283])

In [54]:
# returns total sum of all values
a.sum()

8.4669665985378302

<h2>Calculating the norm</h2>

In [55]:
# calculating the norm of a 2D vector
# norm = sqrt(x**2 + y**2)

# array with 10 coordinates (x,y), find the norm of each coordinate
# 1. square the coordinates, obtaining an array that contains x**2 y**2 elements
# 2. sum those with numpy.sum over the last axis
# 3. take the square root, element-wise with numpy.sqrt

r_i = np.random.rand(10, 2)
norm = np.sqrt((r_i ** 2).sum(axis=1))
print(norm)

[ 0.93195452  0.51958949  1.09060949  0.84416319  1.02655692  0.89153612
  0.9353111   1.00264635  0.68170694  0.95248892]


<h2>Rewriting the particle simulator in NumPy</h2>
...skipped..

<h2>Reaching optimal performance with numexpr</h2>

In [56]:
# numexpr, which optimizes and compiles array expressions on the fly
# Its usage is generally straightforward and is based on a single function--
# numexpr.evaluate. The function takes a string containing an array expression as its first
# argument
import numexpr as ne
a = np.random.rand(10000)
b = np.random.rand(10000)
c = np.random.rand(10000)
d = ne.evaluate('a + b * c')

In [57]:
d

array([ 0.86744142,  0.44805444,  0.8098505 , ...,  0.2550747 ,
        0.89283832,  1.10956487])

<h1>Pandas</h1>

In [58]:
import pandas as pd
patients = [0, 1, 2, 3]
effective = [True, True, False, False]
effective_series = pd.Series(effective, index=patients)

In [59]:
effective_series

0     True
1     True
2    False
3    False
dtype: bool

In [60]:
# we can easily turn our IDs into strings with little effort
patients = ["a", "b", "c", "d"]
effective = [True, True, False, False]
effective_series = pd.Series(effective, index=patients)

In [61]:
effective_series

a     True
b     True
c    False
d    False
dtype: bool

In [62]:
'''create a pd.DataFrame containing four columns that represent the initial and final measurements
of systolic and dyastolic blood pressure for our patients'''

patients = ["a", "b", "c", "d"]
columns = {
    "sys_initial": [120, 126, 130, 115],
    "dia_initial": [75, 85, 90, 87],
    "sys_final": [115, 123, 130, 118],
    "dia_final": [70, 82, 92, 87]
}

df = pd.DataFrame(columns, index=patients)

In [63]:
df

dia_final  dia_initial  sys_final  sys_initial
a         70           75        115          120
b         82           85        123          126
c         92           90        130          130
d         87           87        118          115

In [64]:
effective_series.head()

a     True
b     True
c    False
d    False
dtype: bool

In [65]:
df.head()

dia_final  dia_initial  sys_final  sys_initial
a         70           75        115          120
b         82           85        123          126
c         92           90        130          130
d         87           87        118          115

<h2>Indexing Series and DataFrame objects</h2>

In [66]:
'''Retrieving data from a pd.Series, given its key, can be done intuitively by indexing the
pd.Series.loc attribute'''

effective_series.loc["a"]

True

In [67]:
effective_series.iloc[0]

True

In [68]:
effective_series["a"] # By key

True

In [69]:
effective_series[0] # By position

True

In [70]:
df.loc["a"]

dia_final       70
dia_initial     75
sys_final      115
sys_initial    120
Name: a, dtype: int64

In [71]:
df.iloc[0]

dia_final       70
dia_initial     75
sys_final      115
sys_initial    120
Name: a, dtype: int64

In [72]:
# The loc attribute will index both row and column by key
df.loc["a", "sys_initial"]

120

In [73]:
# iloc version will index row and column by an integer:
df.iloc[0, 1]

75

In [74]:
# Retrieve column by name
df["sys_initial"] # Equivalent to df.sys_initial

a    120
b    126
c    130
d    115
Name: sys_initial, dtype: int64

In [75]:
# Retrieve column by position
df[df.columns[2]] # Equivalent to df.iloc[:, 2]

a    115
b    123
c    130
d    118
Name: sys_final, dtype: int64

In [ ]:
# pandas performance considerations
# create a series with duplicate index
%timeit index = list(range(1000)) + list(range(1000))
# accessing a normal sreies is a O(N) operation
%timeit series = pd.Series(range(2000), index=index)
# sorting will improve look-up scaling to O(log(N))
%timeit series.sort_index(inplace=True)

<h2>database-style operations with Pandas</h2>
<h2>Mapping</h2>

In [77]:
np.log(df.sys_initial) #logarithm of a series

a    4.787492
b    4.836282
c    4.867534
d    4.744932
Name: sys_initial, dtype: float64

In [78]:
df.sys_initial ** 2 #square of a series

a    14400
b    15876
c    16900
d    13225
Name: sys_initial, dtype: int64

In [79]:
np.log(df) # logarithm of a dataframe

dia_final  dia_initial  sys_final  sys_initial
a   4.248495     4.317488   4.744932     4.787492
b   4.406719     4.442651   4.812184     4.836282
c   4.521789     4.499810   4.867534     4.867534
d   4.465908     4.465908   4.770685     4.744932

In [80]:
df ** 2 # square of a dataframe

dia_final  dia_initial  sys_final  sys_initial
a       4900         5625      13225        14400
b       6724         7225      15129        15876
c       8464         8100      16900        16900
d       7569         7569      13924        13225

In [81]:
# Matching index
a = pd.Series([1, 2, 3], index=["a", "b", "c"])
b = pd.Series([4, 5, 6], index=["a", "b", "c"])
a + b

a    5
b    7
c    9
dtype: int64

In [82]:
# Mismatching index
b = pd.Series([4, 5, 6], index=["a", "b", "d"])
b

a    4
b    5
d    6
dtype: int64

In [83]:
# For added flexibility, Pandas exposes the map, apply, and applymap methods that can be
# used to apply specific transformations.

a = pd.Series([1, 2, 3], index=["a", "b", "c"])
def superstar(x):
    return '*' + str(x) + '*'
a.map(superstar)

a    *1*
b    *2*
c    *3*
dtype: object

In [84]:
df.applymap(superstar)

dia_final dia_initial sys_final sys_initial
a      *70*        *75*     *115*       *120*
b      *82*        *85*     *123*       *126*
c      *92*        *90*     *130*       *130*
d      *87*        *87*     *118*       *115*

In [85]:
#apply function columnwise
df.apply(superstar, axis=0)

dia_final      *a    70\nb    82\nc    92\nd    87\nName: dia...
dia_initial    *a    75\nb    85\nc    90\nd    87\nName: dia...
sys_final      *a    115\nb    123\nc    130\nd    118\nName:...
sys_initial    *a    120\nb    126\nc    130\nd    115\nName:...
dtype: object

In [86]:
# apply rowwise
df.apply(superstar, axis=1)

a    *dia_final       70\ndia_initial     75\nsys_f...
b    *dia_final       82\ndia_initial     85\nsys_f...
c    *dia_final       92\ndia_initial     90\nsys_f...
d    *dia_final       87\ndia_initial     87\nsys_f...
dtype: object

In [87]:
# pandas supports efficient numexpr-style expressions with eval method
df.eval("sys_final - sys_initial")

a   -5
b   -3
c    0
d    3
dtype: int64

In [88]:
# In the next example, we compute the difference between
# sys_final and sys_initial, and we store it in the sys_delta column

df.eval("sys_delta = sys_final - sys_initial", inplace=False)

dia_final  dia_initial  sys_final  sys_initial  sys_delta
a         70           75        115          120         -5
b         82           85        123          126         -3
c         92           90        130          130          0
d         87           87        118          115          3

<h2>Grouping, aggregations, and transforms</h2>

In [90]:
'''One of the most appreciated features of Pandas is the simple and concise expression of data
analysis pipelines that requires grouping, transforming, and aggregating the data'''

patients = ["a", "b", "c", "d", "e", "f"]
columns = {
"sys_initial": [120, 126, 130, 115, 150, 117],
"dia_initial": [75, 85, 90, 87, 90, 74],
"sys_final": [115, 123, 130, 118, 130, 121],
"dia_final": [70, 82, 92, 87, 85, 74],
"drug_admst": [True, True, True, True, False, False]
}

df = pd.DataFrame(columns, index=patients)
df

dia_final  dia_initial  drug_admst  sys_final  sys_initial
a         70           75        True        115          120
b         82           85        True        123          126
c         92           90        True        130          130
d         87           87        True        118          115
e         85           90       False        130          150
f         74           74       False        121          117

In [91]:
# You can group the patients according to drug_amst using the
# pd.DataFrame.groupby function
df.groupby('drug_admst')
for value, group in df.groupby('drug_admst'):
    print("Value: {}".format(value))
    print("Group DataFrame:")
    print(group)
    

Value: False
Group DataFrame:
   dia_final  dia_initial  drug_admst  sys_final  sys_initial
e         85           90       False        130          150
f         74           74       False        121          117
Value: True
Group DataFrame:
   dia_final  dia_initial  drug_admst  sys_final  sys_initial
a         70           75        True        115          120
b         82           85        True        123          126
c         92           90        True        130          130
d         87           87        True        118          115


In [92]:
'''Iterating on the DataFrameGroupBy object is almost never necessary, because, thanks to
method chaining, it is possible to calculate group-related properties directly. For example,
we may want to calculate mean, max, or standard deviation for each group. All those
operations that summarize the data in some way are called aggregations and can be
performed using the agg method.'''

df.groupby('drug_admst').agg(np.mean)

dia_final  dia_initial  sys_final  sys_initial
drug_admst                                                
False           79.50        82.00      125.5       133.50
True            82.75        84.25      121.5       122.75

In [94]:
# create missing value for next example
df.loc['a', 'sys_initial'] = None
df

dia_final  dia_initial  drug_admst  sys_final  sys_initial
a         70           75        True        115          NaN
b         82           85        True        123        126.0
c         92           90        True        130        130.0
d         87           87        True        118        115.0
e         85           90       False        130        150.0
f         74           74       False        121        117.0

In [95]:
# missing value is now a known value, using average of other values in the same group
df.groupby('drug_admst').transform(lambda df: df.fillna(df.mean()))

dia_final  dia_initial  sys_final  sys_initial
a         70           75        115   123.666667
b         82           85        123   126.000000
c         92           90        130   130.000000
d         87           87        118   115.000000
e         85           90        130   150.000000
f         74           74        121   117.000000

<h2>Joining</h2>

In [98]:
'''Joins are useful to aggregate data that is scattered among different tables. Let’s say that we
want to include the location of the hospital in which patient measurements were taken in
our dataset. We can reference the location for each patient using the H1, H2, and H3
labels, and we can store the address and identifier of the hospital in a hospital table:'''

hospitals = pd.DataFrame(
{ "name" : ["City 1", "City 2", "City 3"],
"address" : ["Address 1", "Address 2", "Address 3"],
"city": ["City 1", "City 2", "City 3"] },
index=["H1", "H2", "H3"])

hospitals

address    city    name
H1  Address 1  City 1  City 1
H2  Address 2  City 2  City 2
H3  Address 3  City 3  City 3

In [99]:
hospital_id = ["H1", "H2", "H2", "H3", "H3", "H3"]
df['hospital_id'] = hospital_id
df

dia_final  dia_initial  drug_admst  sys_final  sys_initial hospital_id
a         70           75        True        115          NaN          H1
b         82           85        True        123        126.0          H2
c         92           90        True        130        130.0          H2
d         87           87        True        118        115.0          H3
e         85           90       False        130        150.0          H3
f         74           74       False        121        117.0          H3

In [101]:
# Now, we want to find the city where the measure was taken for each patient.
# Pandas allows you to encode the same operation using simple indexing; the
# advantage is that the join will be performed in heavily optimized Cython and with efficient
# hashing algorithms.

cities = hospitals.loc[hospital_id, "city"]
cities

H1    City 1
H2    City 2
H2    City 2
H3    City 3
H3    City 3
H3    City 3
Name: city, dtype: object

In [102]:
'''More advanced joins can also be performed with the pd.DataFrame.join method,
which will produce a new pd.DataFrame that will attach the hospital information for each
patient:'''
result = df.join(hospitals, on='hospital_id')
result.columns

Index(['dia_final', 'dia_initial', 'drug_admst', 'sys_final', 'sys_initial',
       'hospital_id', 'address', 'city', 'name'],
      dtype='object')

In [103]:
result

dia_final  dia_initial  drug_admst  sys_final  sys_initial hospital_id  \
a         70           75        True        115          NaN          H1   
b         82           85        True        123        126.0          H2   
c         92           90        True        130        130.0          H2   
d         87           87        True        118        115.0          H3   
e         85           90       False        130        150.0          H3   
f         74           74       False        121        117.0          H3   

     address    city    name  
a  Address 1  City 1  City 1  
b  Address 2  City 2  City 2  
c  Address 2  City 2  City 2  
d  Address 3  City 3  City 3  
e  Address 3  City 3  City 3  
f  Address 3  City 3  City 3